### ISSUE TITLE
simple mp3 streaming server

### ISSUE THREAD

**Issue by tingyang01** [yomguy/DeeFuzzer#102]
Hello,
I am trying to build a simple mp3 streaming server with your example XML config file.
But I am not getting any result for that.
I've installed DeeFuzzer on Ubuntu 18.04.
I want to get a simple config example file and please guide this.
this is my config:
'''
deefuzzer:
  log: /home/ubuntu/Work/Music_streaming/music_data/station.log
  m3u: /home/ubuntu/Work/Music_streaming/music_data/station.m3u

  stationdefaults:
    control: {mode: 0,
             port: 16001}

    jingles: {dir: /home/ubuntu/Work/Music_streaming/music_data/jingles,
              mode: 0,
              shuffle: 0}

  station:
    control: {mode: 0,
             port: 16001}

    infos: {description: 'My personal best funky playlist ever!',
            genre: 'Various Funk Groove',
            name: 'My best funky station',
            short_name: "My_station",
            url: 'http://parisson.com'}

    jingles: {dir: /home/ubuntu/Work/Music_streaming/music_data/jingles,
              mode: 0,
              shuffle: 1}

    media: {bitrate: 96,
            source: /home/ubuntu/Work/Music_streaming/music_data/mp3,
            format: mp3,
            ogg_quality: 4,
            samplerate: 48000,
            shuffle: 0,
            voices: '1'}

    record: {dir: /home/ubuntu/Work/Music_streaming/music_data/archives,
             mode: 0}

    relay: {author: Unknown,
            mode: 0,
            url: 'http://127.0.0.1:8000/test.mp3'}

    feeds: {mode: 1, rss: 1, json: 0, playlist: 1,
          dir: /home/ubuntu/Work/Music_streaming/music_data/rss,
          enclosure: 0,
          media_url: 'http://localhost/media/'}

    server: {host: 127.0.0.1,
             mountpoint: monitor,
             port: 8000, public: 0,
             sourcepassword: icecast_source_password,
             type: icecast, appendtype: 1}

    twitter: {key: 'your access token key',
              mode: 0, secret: 'your acess token secret key',
              tags: 'parisson deefuzzzer'}
'''
Please share your idea of what's wrong.
Thanks

**Comment by yomguy** [comment]
Hi @tingyang01, deefuzzer is only a client connected on a streaming server. Which server do you use?
If you don't have, you can install icecast2 on the machine itself, setup the source_password as "icecast_source_password", reload it and then start the deefuzzer client.

**Comment by tingyang01** [comment]
thank you, 
I've run this fresh Ubuntu 18.04.
