### ISSUE TITLE
Deefuzzer and Radio DJ

### ISSUE THREAD

**Issue by tingyang01** [yomguy/DeeFuzzer#104]
I am trying to build Radio DJ service with icecast+Deefuzzer(server) and winamp(client).
So I've installed winamp client on my machine.
but I can not configure the server.
I want to know how I can build the Radio DJ server with Deefuzeer.
Thanks,

**Comment by yomguy** [comment]
Hi @tingyang01 

Nope, the DeeFuzzer is only a client to stream files. So you have to choose between DeeFuzzer and Winamp to connect and push to icecast.

**Comment by tingyang01** [comment]
I understand.
Then Could you explain about auto DJ icecast configuration?
Let me know your idea for that.
Thanks

**Comment by yomguy** [comment]
I don't auto DJ icecast conf, but I can say that DeeFuzzer is a kind of auto DJ application as far as it can stream a playlist of audio tracks automatically and indefinitely to a server.
