### ISSUE TITLE
Stream the same content in mp3 + ogg

### ISSUE THREAD

**Issue by ChoiZ** [yomguy/DeeFuzzer#18]
Do you think deefuzzer can stream on multiple icecast mountpoint (with the same media source)? 
- One stream in 192k mp3
- Another one in 48k ogg
(Or two ogg streams, or two mp3 streams)

**Comment by yomguy** [comment]
Transcoding will not be hardcoded for the moment. And I think it easier and safer to transcode all files - many good tools exist for that - and then manage multiple stations in one deefuzzer instance.

**Comment by ChoiZ** [comment]
Ok ;)
