### ISSUE TITLE
Can't read m3u playlist if media.dir is set.

### ISSUE THREAD

**Issue by ChoiZ** [yomguy/DeeFuzzer#21]
If you want to read an m3u file you need to remove "media.dir" parameter.

Maybe we can imagine a "mode" for media node:
- mode = file: read the param "source" as media directory.
- mode = playlist: read the param "source" as a playlist.

With this "mode" maybe "dir" and "m3u" can be the "same" parameter named: "source".

**Comment by achbed** [comment]
Addressed by #47
