### ISSUE TITLE
How can I stream live video from webcam through Deefuzzer ?

### ISSUE THREAD

**Issue by GreG28** [yomguy/DeeFuzzer#24]
Hi,
I tried to found a way for stream live video to Deefuzzer.
But I found nothing on it on the documentation online..

I would like to understand, how to make it.
Maybe, in using ffmpeg for made it like a webM flux ?

**Comment by yomguy** [comment]
https://github.com/yomguy/DeeFuzzer/wiki/HowtoStreamVideo
