### ISSUE TITLE
Empty XML tags causes crash

### ISSUE THREAD

**Issue by achbed** [yomguy/DeeFuzzer#32]
An overly-aggressive XML parser is causing any XML files with empty tag values to crash the entire application.

Example:
`<name></name>` causes a crash, `<name> </name>` does not.

As this is an issue with the parser itself (I belive we're using `xml.dom.minidom`), I'm not sure what we can do here.

**Comment by achbed** [comment]
Suggest that for 0.7, we leave this as addressed by adding documentation to the XML example file.  We can investigate using an alternate XML parser in 0.8.

**Comment by yomguy** [comment]
Yes +1 for this

**Comment by yomguy** [comment]
There is already another parser class based on xml.parsers.expat in tools/xmltodict2.py which I have  already used for others projects with success.
