### ISSUE TITLE
M3U playlist

### ISSUE THREAD

**Issue by yomguy** [yomguy/DeeFuzzer#4]
DeeFuzzer should be able to read a M3U file to get the playlist.

**Comment by achbed** [comment]
Is this addressed by #47 ?

**Comment by yomguy** [comment]
No, by #49. As I proposed in #49, ```<media><playlist>``` remacing ```<media><m3u>``` could check the chmod of the file and execute it if it is executable (i.e. 755), then getting the paths through an os.system() output.

**Comment by achbed** [comment]
Ah, I misunderstood the feature request.  We should take a long hard look at this from a security perspective - calling an unknown outside program could be a huge security hole.

**Comment by yomguy** [comment]
Yes you're right @achbed, this could be dangerous. 
If a script can produce a playlist, it can be executed before the deefuzzer, giving a cue, a m3u or a simple text file. This seems to be sufficient IMHO. OK @sleiman-sleiman?
