### ISSUE TITLE
Playback now starts with track 2 instead of track 1

### ISSUE THREAD

**Issue by achbed** [yomguy/DeeFuzzer#41]
(Affects current dev branch after merge of pull request 39)
Noting here to add to the "fix it before release" queue.

**Comment by yomguy** [comment]
Hi @achbed!
And congrats for the new patestapes.com!
Are your deefuzzer instances stable enough? I'd like to make a release in the next days ;)

**Comment by achbed** [comment]
It's still stopping individual streams for some reason.  I haven't have
time to fully investigate why (spending time with family over the
holidays).  I plan on making some more changes to ease debugging in the
next week or so.  I'd really like to get this nailed down so we can release
a more stable product.  Other than the dropped streams, performance has
been great so far (up to 18 streams at once - we've been rolling out
slowly).

= dw =

On Mon, Jan 5, 2015 at 9:21 AM, Guillaume Pellerin <notifications@github.com

**Comment by yomguy** [comment]
Great news for the 18 streams! 
OK I will also make some tests during this period. 
Have some very good holidays ;)
Cheers

**Comment by achbed** [comment]
Did not happen after #45.  Closing.
