### ISSUE TITLE
Doesn't display song titles correctly

### ISSUE THREAD

**Issue by iyx** [yomguy/DeeFuzzer#44]
At Icecast2 Status page and also in media player it can't handle some (foreign) chars and instead displays a decimal code.

For example **š** gets displayed as `&#353;`, **č** as `&#269;`, etc. (id3 tag info)

**Comment by yomguy** [comment]
Managing char coding is hard an painful, so I need some more tests / hacks on this on various languages.

**Comment by achbed** [comment]
Icecast metadata can have more than just title, but the output in the status XSLT files in the default install does not send them out.  You can modify the files to do that.  The extra metadata does get communicated on the stream I believe.

**Comment by ChoiZ** [comment]
With clementine I have artist and song title in 2 fields because clementine split " - " in metadata info. You can do it on your player (I think it's less difficult to edit player instead of icecast).

**Comment by achbed** [comment]
In most cases, it would be easier to edit your player.  I've written a new ```status-json2.xsl``` file for mine that exports key stream information as a JSON object.  It either uses ```artist``` and/or ```song``` fields, or auto-splits the ```title``` field automatically.

```
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0"><xsl:output indent="no" omit-xml-declaration="yes" method="text" encoding="UTF-8" media-type="application/json"/><xsl:template match="/icestats">{<xsl:for-each select="source"><xsl:if test="position()>1">,</xsl:if>"<xsl:value-of select="translate(@mount,'/','')" />":{"play":{"M3U":"<xsl:value-of select="@mount" />.m3u","XSPF":"<xsl:value-of select="@mount" />.xspf"},"name":"<xsl:value-of select="server_name" />","description":"<xsl:value-of select="server_description" />","type":"<xsl:value-of select="server_type" />","bitrate":"<xsl:value-of select="bitrate" />","listeners":{"current":"<xsl:value-of select="listeners" />","peak":"<xsl:value-of select="listener_peak" />","max":"<xsl:value-of select="max_listeners" />"},"nowplaying":{"artist":"<xsl:choose><xsl:when test="artist"><xsl:value-of select="artist" /></xsl:when><xsl:otherwise><xsl:value-of select='substring-before(title," - ")' /></xsl:otherwise></xsl:choose>","title":"<xsl:choose><xsl:when test="artist"><xsl:value-of select="title" /></xsl:when><xsl:otherwise><xsl:value-of select='substring-after(title," - ")' /></xsl:otherwise></xsl:choose>"}}</xsl:for-each>}</xsl:template></xsl:stylesheet>
```

It's a bit of a run-on sentence to make sure there's no unexpected newlines (which break certain JSON interpreters).

**Comment by yomguy** [comment]
Great! This should be the default setup in icecast :)

**Comment by ChoiZ** [comment]
Out of context (maybe your xsl can be a gist).

We can create "gist" for sharing code (ie: for config in /examples folder).
We can show all revision with gist instead of "comments".

Creating "gist" allow to have:
- yaml config 0.6.6 (revision 1)
- yaml config 0.7 (revision 2)

What do you think about that?

**Comment by yomguy** [comment]
Good point @ChoiZ 
As explain in #20, icecast mountpoints should be configured with UTF8 to allow special chars.

**Comment by achbed** [comment]
I've added this code to the wiki.

**Comment by yomguy** [comment]
Good to have started the wiki. As I wanted to simplify the README, I've put you doc about station folders also in the wiki. Tell me if you are OK with that.

**Comment by ChoiZ** [comment]
I'll check that. For @achbed icecast's config we must add icecast minimum version. (status-json2.xsl is implemented since 1 year in my memory).

**Comment by ChoiZ** [comment]
For station folder doc, I think we have to create a "real" configuration like ```/home/deefuzzer``` for mp3 folder. Define a real shortname ```MyStation``` a name ```MyStation``` too? a gender ```pop, rock…``` and a media.dir ```mp3``` if I understand this path is concat(stationfolder.folder + media.dir)? so equal to ```/home/deefuzzer/mp3```?

**Comment by yomguy** [comment]
Yes @ChoiZ you are welcome to add any more examples to the doc / wiki ;)

**Comment by ChoiZ** [comment]
Ok so I need an answer for "media.dir".
