### ISSUE TITLE
M3U Input does not handle relative paths

### ISSUE THREAD

**Issue by achbed** [yomguy/DeeFuzzer#51]
Currently, using an M3U file as a source does not handle relatives paths.  As specified in https://en.wikipedia.org/wiki/M3U the reader of the M3U should support paths relative to the M3U file location.

**Comment by yomguy** [comment]
OK, I'll fix this.

**Comment by achbed** [comment]
I've got a patch pending.  I just created the issue for reference :)

**Comment by yomguy** [comment]
OK ;)

**Comment by achbed** [comment]
I just pushed another update to the currently pending merge request.  This new path fixes the "relative to the M3U file" part, and undoes the "relative to ```station/base_dir``` fix I had implemented earlier (same merge request).
