### ISSUE TITLE
Is branch "daniel" already used?

### ISSUE THREAD

**Issue by ChoiZ** [yomguy/DeeFuzzer#60]
Can we merge or drop "daniel" branch or @yomguy you want to keep it?

**Comment by yomguy** [comment]
checking and trying to merge.. some hacks are good, but need some tests.

**Comment by yomguy** [comment]
I'm afraid the patch proposed by Daniel Bedeleanu has too much conflicts against the refactored code. Although there is a good idea to hash the playlist, I really don't want to add unstability to the huge work of @achbed for the next RC. So the merge will be delayed until it is fixed and tested.

**Comment by achbed** [comment]
The idea of using a hash for playlist change detection is intriguing.  I can look into that next week.

**Comment by ChoiZ** [comment]
Ok @yomguy thanks for the answer. @achbed I'll try the 0.7 tonight ;) (thanks for your awesome work).
