### ISSUE TITLE
Tag last commit from 0.7

### ISSUE THREAD

**Issue by ChoiZ** [yomguy/DeeFuzzer#61]
@yomguy Can you tag the last 0.7 commit to keep each version in "tags" list?

**Comment by yomguy** [comment]
I will!

**Comment by ChoiZ** [comment]
Ok I think it was already merged on master so… ;-)

**Comment by ChoiZ** [comment]
@yomguy For me (and my tests) 0.7 is ready. Ask to @achbed if it's good.

**Comment by yomguy** [comment]
Released! :)
Thanks a LOT  @achbed and @ChoiZ!!
