### ISSUE TITLE
mountpoint name is back with ".mp3" ".ogg"

### ISSUE THREAD

**Issue by ChoiZ** [yomguy/DeeFuzzer#66]
The extension ".mp3" is back on mountpoint name in 0.7 ;)

We remove it in 0.6.6.

**Comment by achbed** [comment]
It's not present on my config.  Are you specifying one in the config file?

**Comment by ChoiZ** [comment]
I think no, I only add serverdefault node and update media, dir to source. It's the same config i use for 0.6.6

**Comment by achbed** [comment]
Whats' in the serverdefault node?

**Comment by yomguy** [comment]
Maybe we should set the whole mountpoint explicitely in the config, i.e. replacing shortname by mountpoint?

**Comment by achbed** [comment]
The logic on mountpoint naming in 0.7 is as follows:
Use ```station:server:mountpoint``` if specified, OR
Use ```station:info:short_name``` if specified, OR
Use ```default```.

**Comment by yomguy** [comment]
Oh yes, I forgot this new options, perfect @achbed ;)

**Comment by achbed** [comment]
Should the default be 0 instead (if 0.6.6 did indeed change behavior to suppress)?

**Comment by yomguy** [comment]
Maybe because it seems Itunes or other nasty player have bugs with streams urls including an extension. @ChoiZ can you confirm this?

**Comment by achbed** [comment]
See #68 - default for ```appendtype``` is now 0 (suppress output) to match readme notes from 0.6.6

**Comment by ChoiZ** [comment]
Thanks guys, I'll try again and told you.

**Comment by ChoiZ** [comment]
Nice it's works like a charm.
