### ISSUE TITLE
Can't start more than one station at same time with the yaml config format

### ISSUE THREAD

**Issue by ChoiZ** [yomguy/DeeFuzzer#79]
I try to load 3 stations in the same config and I've got Station 2 is stopped and will not be restarted.

I try to load 1 station per config and load 3 configs and the third one:
- Core: Station Station 0 is stopped and will no be restarted.

**Comment by ChoiZ** [comment]
My icecast config source was set to "2" sources…

By the way, the message in the log is not explicit.

**Comment by yomguy** [comment]
Ah, I was about to ask you about your icecast conf :) (very usual situation as it is fixed to 2 by default in many distribs...).
By the way, what is your deefuzzer config file type?

**Comment by ChoiZ** [comment]
I use xml file for my config.

I build my own icecast but the default config value is 2…

**Comment by yomguy** [comment]
OK. I'm re-opening because the bug is effective with yaml config format..

**Comment by ChoiZ** [comment]
Ok ;)
