### ISSUE TITLE
tag 0.6.6

### ISSUE THREAD

**Issue by ChoiZ** [yomguy/DeeFuzzer#81]
Add a tag 0.6.6 on the specific commit.
Maybe it's: 25a88da

**Comment by yomguy** [comment]
Sorry, I don't understand the issue :(

**Comment by ChoiZ** [comment]
Ajouter un tag (git tag) au commit qui correspond à la version 0.6.6

**Comment by yomguy** [comment]
ah ok :)

**Comment by ChoiZ** [comment]
Thanks! It's better for rollback to previous version.
