### ISSUE TITLE
What DeeFuzzer can do?

### ISSUE THREAD

**Issue by mooseh** [yomguy/DeeFuzzer#87]
Hi There

im wondering firstly is there a place where we can ask these questions rather than leave an issue in github? :)

secondly can DeFuzzer receive and input from an encoder?
for example i send a stream with an icy protocol to DeFuzzer and deFuzzer sends to icecast?

Kind Regards
MooseH

**Comment by yomguy** [comment]
Hi @mooseh 
Yes sure you can post question!
The DeeFuzzer doesn't have any open input yet although it can can relay from an external streaming source itself. For example, relaying an icecast stream to another icecast server.
So, at the moment, it is only possible in yur case if the ICY source can provide a port or a mountpoint of its stream.
