### ISSUE TITLE
segmentation fault (core dumped)

### ISSUE THREAD

**Issue by jawak** [yomguy/DeeFuzzer#90]
![Screenshot from 2019-07-04 14-31-40](https://user-images.githubusercontent.com/25633643/60647713-8532d800-9e68-11e9-817c-9f08b82cc805.png)
My config

> <deefuzzer>
    <log>./log/station.log</log>
    <m3u>./log/station.m3u</m3u>
    <stationdefaults>
        <control>
            <mode>0</mode>
            <port>16001</port>
        </control>
        <jingles>
            <dir>/path/to/jingles</dir>
            <mode>0</mode>
            <shuffle>1</shuffle>
        </jingles>
    </stationdefaults>
    <station>
        <control>
            <mode>0</mode>
            <port>16001</port>
        </control>
        <infos>
            <description>My personal best funky playlist ever !</description>
            <genre>Various Funk Groove</genre>
            <name>My best funky station</name>
            <short_name>My_station</short_name>
            <url>http://parisson.com</url>
        </infos>
        <jingles>
            <dir>/path/to/jingles</dir>
            <mode>0</mode>
            <shuffle>1</shuffle>
        </jingles>
        <media>
            <bitrate>96</bitrate>
            <source>./media/</source>
            <format>mp3</format>
            <ogg_quality>4</ogg_quality>
            <samplerate>48000</samplerate>
            <shuffle>0</shuffle>
            <voices>2</voices>
        </media>
        <record>
            <dir>/path/to/archives</dir>
            <mode>0</mode>
        </record>
        <relay>
            <author>Unknown</author>
            <mode>0</mode>
            <url>http://127.0.0.1:8000/telecaster_live.mp3</url>
        </relay>
        <feeds>
            <mode>1</mode>
            <rss>1</rss>
            <json>0</json>
            <playlist>1</playlist>
            <dir>/path/to/rss/</dir>
            <enclosure>1</enclosure>
            <media_url>http://localhost/media/</media_url>
        </feeds>
        <server>
            <host>localhost</host>
            <mountpoint>pop</mountpoint>
            <port>8000</port>
            <public>0</public>
            <sourcepassword>hackme</sourcepassword>
            <type>icecast</type>
            <appendtype>1</appendtype>
        </server>
        <twitter>
            <key>your access token key</key>
            <mode>0</mode>
            <secret>your access token secret key</secret>
            <tags>parisson deefuzzer</tags>
        </twitter>
    </station>

</deefuzzer>

station log
2019-07-04 14:29:19,325 INFO Core: Starting DeeFuzzer
2019-07-04 14:29:19,325 INFO Core: Using libshout version 2.4.1
2019-07-04 14:29:19,325 INFO Core: Number of stations : 1
2019-07-04 14:29:19,326 INFO Core: Loading new stations
2019-07-04 14:29:19,327 INFO Station http://localhost:8000/pop.mp3: Opening pop - My best funky station
2019-07-04 14:29:19,327 INFO Core: Started station Station 0
2019-07-04 14:29:19,328 INFO Core: Writing M3U file to : ./log/station.m3u
2019-07-04 14:29:19,333 INFO Station http://localhost:8000/pop.mp3: Channel available.
2019-07-04 14:29:19,334 INFO Station http://localhost:8000/pop.mp3: channel connected
2019-07-04 14:29:19,334 INFO Station http://localhost:8000/pop.mp3: Generating new playlist (3 tracks)
2019-07-04 14:29:19,339 INFO Station http://localhost:8000/pop.mp3: DeeFuzzing:  id = 2, name = Iwan Fals - Satu Satu my-free-mp3s.com .mp3

**Comment by yomguy** [comment]
Hi @jawak 
Sorry I didn't catch your first message. Usually deefuzzer crashed because of a bad config file setup.
Is it now better for you?

**Comment by jawak** [comment]
@yomguy 
upgrade python-shout 0.2.5
Seems works well.
