### ISSUE TITLE
deefuzzer install failer: ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by robnoordt** [yomguy/DeeFuzzer#92]
Hi,

On a raspberry pi 3, running Debian Stretch and python 3.6.5, it does not work to install deefuzzer. Below the last part of the output from the putty screen. I am making use of a screenreader and because of that I cannot copy the whole screen. But II hope you can help to find a solution.
Welkome sugesions!
==>>
collected packages: pyliblo
  Building wheel for pyliblo (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5gey342u/pyliblo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5gey342u/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-efbn8in9 --python-tag cp36
       cwd: /tmp/pip-install-5gey342u/pyliblo/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_ext
  cythoning src/liblo.pyx to src/liblo.c
  /usr/local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-5gey342u/pyliblo/src/liblo.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'liblo' extension
  creating build
  creating build/temp.linux-armv7l-3.6
  creating build/temp.linux-armv7l-3.6/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.6m -c src/liblo.c -o build/temp.linux-armv7l-3.6/src/liblo.o -fno-strict-aliasing -Werror-implicit-function-declaration -Wfatal-errors
  src/liblo.c:599:19: fatal error: lo/lo.h: No such file or directory
   #include "lo/lo.h"
                     ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyliblo
  Running setup.py clean for pyliblo
Failed to build pyliblo
Installing collected packages: pyliblo, deefuzzer
    Running setup.py install for pyliblo ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5gey342u/pyliblo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5gey342u/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-aiml3b4i/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-5gey342u/pyliblo/
    Complete output (14 lines):
    running install
    running build
    running build_ext
    skipping 'src/liblo.c' Cython extension (up-to-date)
    building 'liblo' extension
    creating build
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.6m -c src/liblo.c -o build/temp.linux-armv7l-3.6/src/liblo.o -fno-strict-aliasing -Werror-implicit-function-declaration -Wfatal-errors
    src/liblo.c:599:19: fatal error: lo/lo.h: No such file or directory
     #include "lo/lo.h"
                       ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5gey342u/pyliblo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5gey342u/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-aiml3b4i/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
root@raspberry3:~#

**Comment by yomguy** [comment]
@robnoordt 
As for #91, a dependency is missing here (liblo-dev), try:
```
sudo apt-get install python-pip python-dev python-liblo \
                     python-mutagen python-pycurl python-yaml \
                     libshout3-dev librtmp-dev liblo-dev \
                     libcurl4-openssl-dev libmysqlclient-dev
```

**Comment by robnoordt** [comment]
Here are the results;

root@raspberry3:~# sudo apt-get install python-pip python-dev python-liblo python-mutagen python-pycurl python-yaml libshout3-dev librtmp-dev liblo-dev libcurl4-openssl-dev libmysqlclient-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libmysqlclient-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libmysqlclient-dev' has no installation candidate
root@raspberry3:~#
root@raspberry3:~#
It seeams misql has been chanched to maria db in Stretsh. So give it a tri;

root@raspberry3:~# apt install libmariadbclient-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libmariadbclient-dev is already the newest version (10.1.38-0+deb9u1).
libmariadbclient-dev set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@raspberry3:~#

End again tried install deefuzzer
No changes;

error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hqnyt_to/pyliblo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hqnyt_to/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-b4bybruc/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
root@raspberry3:~#

From the website PyPI:
https://pypi.org/project/mysqlclient/

root@raspberry3:~# apt-get install python-dev default-libmysqlclient-dev # Debian / Ubuntu
Reading package lists... Done
Building dependency tree
Reading state information... Done
default-libmysqlclient-dev is already the newest version (1.0.2).
python-dev is already the newest version (2.7.13-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@raspberry3:~#

Here you can sea all installed packages;

root@raspberry3:~# pip list
Package           Version
----------------- ----------
certifi           2019.11.28
chardet           3.0.4
Cython            0.29.14
distribute        0.7.3
future            0.18.2
gcc               0.1
idna              2.8
mutagen           1.43.0
mysqlclient       1.4.6
oauthlib          3.1.0
pip               19.3.1
pycurl            7.43.0.3
python-shout      0.2.6
python-twitter    3.5
PyYAML            5.2
requests          2.22.0
requests-oauthlib 1.3.0
setuptools        42.0.2
urllib3           1.25.7
wheel             0.33.6
root@raspberry3:~#


One other tri to install deefuzzer results in below;

root@raspberry3:~# pip install deefuzzer
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting deefuzzer
  Using cached https://www.piwheels.org/simple/deefuzzer/DeeFuzzer-0.7.2-py3-none-any.whl
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/site-packages (from deefuzzer) (5.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from deefuzzer) (42.0.2)
Requirement already satisfied: pycurl in /usr/local/lib/python3.6/site-packages (from deefuzzer) (7.43.0.3)
Requirement already satisfied: python-twitter in /usr/local/lib/python3.6/site-packages (from deefuzzer) (3.5)
Requirement already satisfied: mutagen in /usr/local/lib/python3.6/site-packages (from deefuzzer) (1.43.0)
Collecting pyliblo
  Using cached https://files.pythonhosted.org/packages/c0/da/4b8052ab5aa07952d7fe7b068d737a042e76373573eadd340f7550eddea9/pyliblo-0.10.0.tar.gz
Requirement already satisfied: python-shout in /usr/local/lib/python3.6/site-packages (from deefuzzer) (0.2.6)
Requirement already satisfied: mysqlclient in /usr/local/lib/python3.6/site-packages (from deefuzzer) (1.4.6)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.6/site-packages (from python-twitter->deefuzzer) (1.3.0)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from python-twitter->deefuzzer) (2.22.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/site-packages (from python-twitter->deefuzzer) (0.18.2)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/site-packages (from requests-oauthlib->python-twitter->deefuzzer) (3.1.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->python-twitter->deefuzzer) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->python-twitter->deefuzzer) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->python-twitter->deefuzzer) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->python-twitter->deefuzzer) (3.0.4)
Building wheels for collected packages: pyliblo
  Building wheel for pyliblo (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z61m5abp/pyliblo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z61m5abp/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-lmzg9qyj --python-tag cp36
       cwd: /tmp/pip-install-z61m5abp/pyliblo/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_ext
  cythoning src/liblo.pyx to src/liblo.c
  /usr/local/lib/python3.6/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /tmp/pip-install-z61m5abp/pyliblo/src/liblo.pxd
    tree = Parsing.p_module(s, pxd, full_module_name)
  building 'liblo' extension
  creating build
  creating build/temp.linux-armv7l-3.6
  creating build/temp.linux-armv7l-3.6/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.6m -c src/liblo.c -o build/temp.linux-armv7l-3.6/src/liblo.o -fno-strict-aliasing -Werror-implicit-function-declaration -Wfatal-errors
  src/liblo.c:599:19: fatal error: lo/lo.h: No such file or directory
   #include "lo/lo.h"
                     ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyliblo
  Running setup.py clean for pyliblo
Failed to build pyliblo
Installing collected packages: pyliblo, deefuzzer
    Running setup.py install for pyliblo ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z61m5abp/pyliblo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z61m5abp/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1tkdl_vr/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-z61m5abp/pyliblo/
    Complete output (14 lines):
    running install
    running build
    running build_ext
    skipping 'src/liblo.c' Cython extension (up-to-date)
    building 'liblo' extension
    creating build
    creating build/temp.linux-armv7l-3.6
    creating build/temp.linux-armv7l-3.6/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include/python3.6m -c src/liblo.c -o build/temp.linux-armv7l-3.6/src/liblo.o -fno-strict-aliasing -Werror-implicit-function-declaration -Wfatal-errors
    src/liblo.c:599:19: fatal error: lo/lo.h: No such file or directory
     #include "lo/lo.h"
                       ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-z61m5abp/pyliblo/setup.py'"'"'; __file__='"'"'/tmp/pip-install-z61m5abp/pyliblo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-1tkdl_vr/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
root@raspberry3:~# +

any other suggestions?

**Comment by yomguy** [comment]
@robnoordt oh! libmysqlclient-dev seems not available anymore, we should then install libmariadbclient-dev instead. 

Your last command did not installed other necessary packages, so please install all of them: 
```
sudo apt-get install python-pip python-dev python-liblo \
                         python-mutagen python-pycurl python-yaml \
                         libshout3-dev librtmp-dev liblo-dev \
                         libcurl4-openssl-dev libmariadbclient-dev
```
Fixed in #743ca82

**Comment by robnoordt** [comment]
Thanks again for your responce. Almost there.
Here comes mi results;
apt install python-pip python-dev python-liblo -y
apt install python-mutagen python-pycurl python-yaml -y -y
apt install libshout3-dev librtmp-dev liblo-dev -y                        
apt install libcurl4-openssl-dev libmariadbclient-dev -y

Nouw installed all succesfullyu!
After tthis the deefuzzerr install;
==>>

root@raspberry3:~# pip install deefuzzer
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting deefuzzer
  Downloading https://www.piwheels.org/simple/deefuzzer/DeeFuzzer-0.7.3-py3-none-any.whl (58kB)
     |████████████████████████████████| 61kB 549kB/s
Requirement already satisfied: python-twitter in /usr/local/lib/python3.6/site-packages (from deefuzzer) (3.5)
Requirement already satisfied: mutagen in /usr/local/lib/python3.6/site-packages (from deefuzzer) (1.43.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from deefuzzer) (42.0.2)
Requirement already satisfied: python-shout==0.2.6 in /usr/local/lib/python3.6/site-packages (from deefuzzer) (0.2.6)
Requirement already satisfied: pycurl in /usr/local/lib/python3.6/site-packages (from deefuzzer) (7.43.0.3)
Requirement already satisfied: mysqlclient in /usr/local/lib/python3.6/site-packages (from deefuzzer) (1.4.6)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/site-packages (from deefuzzer) (5.2)
Collecting pyliblo
  Using cached https://files.pythonhosted.org/packages/c0/da/4b8052ab5aa07952d7fe7b068d737a042e76373573eadd340f7550eddea9/pyliblo-0.10.0.tar.gz
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from python-twitter->deefuzzer) (2.22.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.6/site-packages (from python-twitter->deefuzzer) (1.3.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/site-packages (from python-twitter->deefuzzer) (0.18.2)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->python-twitter->deefuzzer) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->python-twitter->deefuzzer) (1.25.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->python-twitter->deefuzzer) (2019.11.28)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->python-twitter->deefuzzer) (3.0.4)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/site-packages (from requests-oauthlib->python-twitter->deefuzzer) (3.1.0)
Building wheels for collected packages: pyliblo
  Building wheel for pyliblo (setup.py) ... done
  Created wheel for pyliblo: filename=pyliblo-0.10.0-cp36-cp36m-linux_armv7l.whl size=305829 sha256=9f59120b6d32f001c5444585ed0fcf60bd893986be6832712c591346c87f76c2
  Stored in directory: /root/.cache/pip/wheels/63/18/20/4124f951263fa3daf438b19eafc48ab6a803508d585d69a902
Successfully built pyliblo
Installing collected packages: pyliblo, deefuzzer
Successfully installed deefuzzer-0.7.3 pyliblo-0.10.0
root@raspberry3:~#

Ahha, that looks a lot better, isnt it?
Ok, here komes the final.

root@raspberry3:~# deefuzzer /etc/deefuzzer/deefuzzer.xml
Traceback (most recent call last):
  File "/usr/local/bin/deefuzzer", line 8, in <module>
    import deefuzzer
  File "/usr/local/lib/python3.6/site-packages/deefuzzer/__init__.py", line 1, in <module>
    from core import *
ModuleNotFoundError: No module named 'core'
root@raspberry3:~#
Ad the end of almost all;
Hopefully this is the last truble to getting it work.

installed the moduule utils-core · PyPI
https://pypi.org/project/utils-core/

No result on this. I do not know if this could be a solution but just tried it.

Searched on google for: ModuleNotFoundError: No module named 'core'
Fond: https://stackoverflow.com/questions/35330964/no-module-named-core-when-using-pyping-for-python-3
but I do not realy understand what it means.
Do you have a stap bi stap solution for this?

**Comment by yomguy** [comment]
Hi @robnoordt 
The current version is compatible with python 2.7 only **but** I have just prepared a python 3 version.
Please stay tuned, I will push it today if everything is fine ;)

**Comment by robnoordt** [comment]
Oh, that will be great! Looking forward.

**Comment by yomguy** [comment]
@robnoordt 0.8.0 is now available, compatible with Python 3. 
See https://github.com/yomguy/DeeFuzzer#installation for new dependencies.
Enjoy! ;-)

**Comment by robnoordt** [comment]
[Errno 2] No such file or directory: '/etc/deefuzzer/deefuzzer.yaml'
root@raspberry3:~# deefuzzer
 deefuzzer : easy and instant media streaming tool
 version : 0.8.0
 running on system : Linux

 Copyright (c) 2007-2019 Guillaume Pellerin <yomguy@parisson.com>
 All rights reserved.

 This software is licensed as described in the file COPYING, which
 you should have received as part of this distribution. The terms
 are also available at https://github.com/yomguy/DeeFuzzer/blob/master/LICENSE

 depends:  python, python-dev, python-xml, python-shout | shout-python, libshout3,
           libshout3-dev, python-mutagen, python-pycurl

 recommends: icecast2, python-twitter, python-liblo | pyliblo (>= 0.26)

 Usage : deefuzzer [file]

  where [file] is the path for a XML config file.

  Edit an example in example/deefuzzer.xml
  and then start one or more stations:

  $ deefuzzer example/deefuzzer.xml

 see http://github.com/yomguy/DeeFuzzer for more details and debugging.

[1]+  Exit 1                  deefuzzer /etc/deefuzzer/deefuzzer.yaml
root@raspberry3:~#

**Comment by robnoordt** [comment]
After installing/updating the install packages, that worked out Ok,
Just in the commandline deefuzzer;
[Errno 2] No such file or directory: '/etc/deefuzzer/deefuzzer.yaml'
root@raspberry3:~# deefuzzer
 deefuzzer : easy and instant media streaming tool
 version : 0.8.0
 running on system : Linux

 Copyright (c) 2007-2019 Guillaume Pellerin <yomguy@parisson.com>
 All rights reserved.

 This software is licensed as described in the file COPYING, which
 you should have received as part of this distribution. The terms
 are also available at https://github.com/yomguy/DeeFuzzer/blob/master/LICENSE

 depends:  python, python-dev, python-xml, python-shout | shout-python, libshout3,
           libshout3-dev, python-mutagen, python-pycurl

 recommends: icecast2, python-twitter, python-liblo | pyliblo (>= 0.26)

 Usage : deefuzzer [file]

  where [file] is the path for a XML config file.

  Edit an example in example/deefuzzer.xml
  and then start one or more stations:

  $ deefuzzer example/deefuzzer.xml

 see http://github.com/yomguy/DeeFuzzer for more details and debugging.

[1]+  Exit 1                  deefuzzer /etc/deefuzzer/deefuzzer.yaml
root@raspberry3:~#

Looks Ok but?

deefuzzer /etc/deefuzzer/deefuzzer.yaml &

root@raspberry3:~# deefuzzer /etc/deefuzzer/deefuzzer.yaml
Traceback (most recent call last):
  File "/usr/local/bin/deefuzzer", line 56, in <module>
    main()
  File "/usr/local/bin/deefuzzer", line 48, in main
    d = deefuzzer.core.DeeFuzzer(sys.argv[-1])
  File "/usr/local/lib/python3.6/site-packages/deefuzzer/core.py", line 56, in __init__
    self.conf = get_conf_dict(self.conf_file)
  File "/usr/local/lib/python3.6/site-packages/deefuzzer/tools/utils.py", line 98, in get_conf_dict
    confile = open(file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/etc/deefuzzer/deefuzzer.yaml'
root@raspberry3:~#

**Comment by robnoordt** [comment]
After installing/updating the install packages, that worked out Ok,
Just in the commandline deefuzzer;
[Errno 2] No such file or directory: '/etc/deefuzzer/deefuzzer.yaml'
root@raspberry3:~# deefuzzer
 deefuzzer : easy and instant media streaming tool
 version : 0.8.0
 running on system : Linux

 Copyright (c) 2007-2019 Guillaume Pellerin <yomguy@parisson.com>
 All rights reserved.

 This software is licensed as described in the file COPYING, which
 you should have received as part of this distribution. The terms
 are also available at https://github.com/yomguy/DeeFuzzer/blob/master/LICENSE

 depends:  python, python-dev, python-xml, python-shout | shout-python, libshout3,
           libshout3-dev, python-mutagen, python-pycurl

 recommends: icecast2, python-twitter, python-liblo | pyliblo (>= 0.26)

 Usage : deefuzzer [file]

  where [file] is the path for a XML config file.

  Edit an example in example/deefuzzer.xml
  and then start one or more stations:

  $ deefuzzer example/deefuzzer.xml

 see http://github.com/yomguy/DeeFuzzer for more details and debugging.

[1]+  Exit 1                  deefuzzer /etc/deefuzzer/deefuzzer.yaml
root@raspberry3:~#

Looks Ok but?

deefuzzer /etc/deefuzzer/deefuzzer.yaml &

root@raspberry3:~# deefuzzer /etc/deefuzzer/deefuzzer.yaml
Traceback (most recent call last):
  File "/usr/local/bin/deefuzzer", line 56, in <module>
    main()
  File "/usr/local/bin/deefuzzer", line 48, in main
    d = deefuzzer.core.DeeFuzzer(sys.argv[-1])
  File "/usr/local/lib/python3.6/site-packages/deefuzzer/core.py", line 56, in __init__
    self.conf = get_conf_dict(self.conf_file)
  File "/usr/local/lib/python3.6/site-packages/deefuzzer/tools/utils.py", line 98, in get_conf_dict
    confile = open(file, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/etc/deefuzzer/deefuzzer.yaml'
root@raspberry3:~#

**Comment by yomguy** [comment]
@robnoordt well the error message is explicit : `No such file or directory: '/etc/deefuzzer/deefuzzer.yaml'`
So you miss a right path for your config file.

**Comment by robnoordt** [comment]
Ok, but where or wat should be the config file? And Where to find? Sorry, I am just a hobbyisst, not spesialist...
